### ISSUE TITLE
Game balance problem

### ISSUE THREAD

**Issue by GalaxyZEROX** [coolsimulations/SurvivalPlus-Lightsabers#4]
Excuse me, can you reduce the damage of white lightsaber? Pearls are too easy to get, and their power is higher than that of blue, red and green lightsabers. . .

**Comment by coolsimulations** [comment]
No. White has a higher damage value due to its rarity in Star Wars. Also, as of 1.17 Pearls are a lot harder to find which balances this issue.

**Comment by GalaxyZEROX** [comment]
Can I modify versions before version 1.17 separately?

**Comment by GalaxyZEROX** [comment]
Because pearls can often be found in the sea from version 1.12.2 to version 1.16.5.

**Comment by coolsimulations** [comment]
I deleted your “new” issue page because it was not an issue and is a duplicate of this page. Creating a “new” issue is not how you will re-open a closed issue. You did already mention this [before](https://www.curseforge.com/minecraft/mc-mods/survivalplus-lightsabers?comment=79 ) in which I said I would think about before updating. Although I didn’t further reply to that comment I decided it was fine how it was. Regarding that “new issue” and your comments, pearls spawning in the ocean is intentional gameplay.

To be honest, white lightsabers are fine just the way they are. Personally, when I play, I generally skip straight to the Darksaber so pearl spawns doesn’t affect how I play. This is not always the case but it’s important to point out that in the main survival world I’m playing right now, the nearest ocean is 3000 blocks away from spawn so I actually found sapphires before pearls. Similarly, players typically need to go the Nether first to get blaze rods to get to the end before visiting an ocean so going by that “speed running” logic they should find one of the other crystals first. But anyway that’s not important to this “issue”.

Another note, compared to the Purple Lightsaber the White one does only **2 damage more**! And compared to the regulars it’s only a **difference of 4**. Even with regular lightsabers you are still one-shoting vanilla mobs (aside from Endermen) and that doesn’t even include sharpness enchantments that you can apply to it. 2-4 damage does not make much of a difference when it’s ready at a base of 20 damage.

Technically, yes, if you can setup the workspace with SurvivalPlus and other related dependencies then you can compile an edited file. **Important note: You cannot distribution any fork or edit in any way! Any changes you make are for private use only because if its license.**

Final note: I’m not 100% sure if this comment sounds hash in any way, but modding is a hobby. Usually, I’m very open to suggestions (such as your entity drops cooking, sword blocking support, deactivating the lightsaber when thrown, etc) but this is not one of them. The last batch of updates took me over a hundred hours to complete and release. Through which I do many tests of ore spawning rates, trades/amour balancing, and seriously play a new survival world for a dozen hours to find hidden issues and bugs before I release anything. I’m simply trying to say that I’ve made my decision.
